### ISSUE TITLE
Announce flag changes

### ISSUE THREAD

**Issue by butterscotchstallion** [ncoevoet/ChanTracker#15]
" SET VERBOSE OPS sends a notice to the channel operators when someone makes changes to the access lists."

It would be useful to relay this information to the announcement channel. Maybe there could be an option like "announceFlagChanges".

**Comment by ncoevoet** [comment]
Until there is a subset feature to only announce channel's notices made by some specific users/bots/services, you can take a look at !config help supybot.plugins.ChanTracker.announceNotice which will forward channel's notices to logChannel ( per channel's settings )
