### ISSUE TITLE
edit and editandmark commands don't work to make a ban permanant

### ISSUE THREAD

**Issue by Zoddo** [ncoevoet/ChanTracker#19]
In the `edit` and `editandmark`, `-1` isn't accepted as a duration to make a ban permanant.

`edit` return the help while `editandmark` return
```
item not found, already removed or not enough rights to modify it
```

The help of `editandmark` also states we can leave empty the duration to set the ban forever, but the same problem happens when doing that.

**Comment by ncoevoet** [comment]
hi
you could try -1s it should work, i think the help is missleading,
i will check.

**Comment by ncoevoet** [comment]
In fact, if the item is sets to never expires (which is the default, until you change the default duration) you will get such error, an item with a expires time will accepts -1s
