### ISSUE TITLE
feature request: ban the account with /mode +b $a:accountname

### ISSUE THREAD

**Issue by hboetes** [ncoevoet/ChanTracker#21]
Hi there,
To keep track of banmasks and make them hard to avoid we use banmasks with with the account name exclusively on our channel. I don’t think that possible right now or is it? Please consider adding it or please explain how to do it.
Thanks!

**Comment by hboetes** [comment]
That is, if it is a registered user, of course. We’ve set the channel on /mode +q ~$a so that makes a lot of sense, almost everyone is registered.

**Comment by hboetes** [comment]
For example:

```
channel ban add #channel $a:account
Error: ‘$a:account’ is not a valid nick or hostmask.
```

This is of course a valid hostmask on freenode.

**Comment by teward** [comment]
@hboetes Correction: it is a valid **ban pattern**, but not a valid *hostmask*.  A valid *hostmask* would match the pattern of `nick!ident@hostname#gecos` (such as `*!*@unaffiliated/account`).  (There is a difference)

**Comment by hboetes** [comment]
Hmmm yes you are right, it is not a valid hostmask, but it is a valid way to identify and ban someone, although the account name has to be looked up with `/whois`, Would that be a problem?

**Comment by teward** [comment]
I'm not as well informed about the internals of how difficult it would be to do that `/whois` step reliably, so I'm probably not the best person to answer that question.

This said, this is from the README:

> The plugin also supports extended bans/quiets including $r, $x, $a, $j (real name, full match and account name, respectively). 

So if this is no longer the case, evidenced by your issue post here, then it sounds like there's been a regression somewhere with that featureset.

**Comment by hboetes** [comment]
Yes I read that part as well. But I can’t find anything in the code nor the docs on how to actually use that part or if is really implemented. I assumed that  I should use $a:account. But I might as well be wrong.

**Comment by ncoevoet** [comment]
if you !info <id> or !getmask <nick> you can see that the bot knows exactly user's account and gecos

**Comment by ncoevoet** [comment]
you can try to set supybot.protocols.irc.strictRfc to False if you want to let Channel's plugin doing that

**Comment by hboetes** [comment]
ok, let me try to explain the issue a bit better.

* All users have to be registered on to be able to speak since we mute unidentified users.
* If the bot detects misbehaviour from a user I’d like it to set an $a:account ban since that’s the hardest to evade.
