### ISSUE TITLE
feature request: ban the account with /mode +b $a:accountname

### ISSUE THREAD

**Issue by hboetes** [ncoevoet/ChanTracker#22]
ok, let me try to explain the issue a bit better.

* All users on our channel have to be registered to be able to speak since we mute unidentified users.
* If the bot detects misbehaviour from a user I’d like it to set an $a:account ban since that’s the hardest to evade.

**Comment by ncoevoet** [comment]
it's the easier to evade : the user only have to change his nick, group the new one, and change his account name, but i suppose i can provide an option to choose the account ban if user is registered

**Comment by ncoevoet** [comment]
if the answer i provided is enough for you, could i close this ticket ?

**Comment by hboetes** [comment]
Hmm somehow my answer didn’t make it. No it’s not easier to evade. Like already mentioned: “All users on our channel have to be registered to be able to speak since we mute unidentified users.”

So they can evade but can’t speak, which makes their behaviour easy to spot by opers.

So being able to set $a:account bans would be a major plus. Thanks for considering to implement it.

**Comment by hboetes** [comment]
you’ve closed the ticket, straight after the commit. But there is no
documentation and I still want to ask how it works.

For instance I updated to the development branch, restarted my bot and
tried:

13:53        Han| channel ban add #mychannel $a:sometroll
13:53      mybot| Error: ‘$a:sometroll’ is not a valid nick or hostmask.
14:03        Han| config channel #mychannel
supybot.plugins.ChanTracker.useAccountBanIfPossible
14:03      mybot| Error:
‘supybot.plugins.ChanTracker.useAccountBanIfPossible’ is not a valid
configuration variable.
14:03        Han| config supybot.plugins.ChanTracker.useAccountBanIfPossible
14:03      mybot| Error:
‘supybot.plugins.ChanTracker.useAccountBanIfPossible’ is not a valid
configuration variable.

**Comment by ncoevoet** [comment]
`channel ban add` is a Channel's plugin command which has nothing to do with chantracker, if you want to use such command change set supybot.protocols.irc.strictRfc to False

to use the new property supybot.plugins.ChanTracker.useAccountBanIfPossible, switch you branch to develop, ( you need a recent version of limnoria )
once it's done, and you enabled the feature, you can use it with !b nick 10s test or !e,!i,!q !note
