### ISSUE TITLE
kick on bans not working

### ISSUE THREAD

**Issue by nirik** [ncoevoet/ChanTracker#30]
```
config help supybot.plugins.ChanTracker.kickMode
 bot will kick affected users when mode is triggered, use with caution, if an op bans *!*@*, bot will kick everyone on the channel  (Current value: b)
config help supybot.plugins.ChanTracker.kickOnMode
 bot will kick affected users when kickMode is triggered by someone, use with caution  (Current value: True)
```

kickMode is set, but on b calls it never kicks the user. :( This worked in previous versions...

**Comment by orcus-de** [comment]
hi niko - I observed the same behavior (might be able to point at least to something)

While working on the HOP-support (started working on a fork from 1.4)  !b did always result in a kick
no matter if   !config supybot.plugins.ChanTracker.kickOnMode   has been set to True or False

Going forward and backwards through my local version, I noticed this behavior already existed with a
copy of master.zip (unmodified) of the 1.4 version, which I downloaded at 2020-09-05.

As searching for the "right" places to apply my changes for allowing HOP additionally to OP took me some time I had to reintegrate with an newer version of master, where the behavior turned exactly upside down:

No matter if   !config supybot.plugins.ChanTracker.kickOnMode   has been set to True or False
kick gets never performed (I retested it last night/today)

although I cant exclude it's related to my modifications // the merged version you did create for 1.5, there are some more changes (besides HOP-handling) on ChanTracker - could be it helps you to track down, what did change to affect the behavior

to get back to a working version

`ChanTracker-master-mod-minimal-switched/plugin.py` is the version before I merged against the updated version from master
`ChanTracker-2020-09-28-branch-version/plugin.py` is the version, which I did offer to you

```
14:57 demo@debian10 : ~/spotbot-setup/plugins/modified-ChanTracker
2002 >diff ChanTracker-master-mod-minimal-switched/plugin.py ChanTracker-2020-09-28-branch-version/plugin.py 
81c81
<     if n.ip != None and '@' in pattern and mcidr.match(pattern.split('@')[1]):
---
>     if n.ip != None and '@' in pattern and n.ip.find('*') == -1 and mcidr.match(pattern.split('@')[1]):
86c86
<     elif n.ip != None and '@' in pattern and m6cidr.match(pattern.split('@')[1]):
---
>     elif n.ip != None and '@' in pattern and n.ip.find('*') == -1 and m6cidr.match(pattern.split('@')[1]):
217c217
<                 host = '*%s' % host.split('ip.')[1]
---
>                 host = '*ip.%s' % host.split('ip.')[1]
227d226
<                         (nick,i,h) = ircutils.splitHostmask(n.prefix)
232,233d230
<         if 'gateway/' in host and '/x-' in host and not 'vpn/' in host:
<             host = '%s/*' % host.split('/x-')[0]
2734a2732,2736
>                                     f = None
>                                     if self.registryValue('announceInTimeEditAndMark',channel=channel):
>                                         if self.registryValue('announceBotMark',channel=channel):
>                                             f = self._logChan
>                                     i.submark(irc,channel,'b',best,"permanent ban %s" % ban,irc.prefix,self.getDb(irc.network),f,self)
3237a3240,3243
>             return True
>         if ircdb.checkCapability(n.prefix, 'trusted'):
>             return True
>         if ircdb.checkCapability(n.prefix, 'protected'):

```
Hope it helps - cu - have fun

**Comment by orcus-de** [comment]
You are mistaking me - this are NOT my changes but the differences coming from master that I noticed on migrating my local modifications for HOB-support (as I took me some time to find my route through ChanServer to find all relevant locations that time I had to merge my modifactions against it) 

Just compare your according version before you integrated the HOP feature against the 1.4 version from around 2020-09-05 and you will likely end up with the same diff-output..

---

With the 1.4 version from that date (the date I did download a master.zip)
the original behavior has been:

No matter how `supybot.plugins.ChanTracker.kickOnMode` has been set, it did always kick with a !b

At the time I wanted to integrate, master has moved forward and the behavior turned upside down == if will never kick, no matter how `kickOnMode ` is set.

And the diff are the changes coming from master...

---

The ban (and removing it after being expired) works as expected, so does the banmask work - it's the kick not taking place with the newer version.

--- 

I do not want to bother you with my problems, but thought you might be intersted in details I did observ in case you care about.

Have fun, and a happy new 2021

**Comment by ncoevoet** [comment]
as i said, you have to check !affect <id> to know if the bot computes properly who is affected by a ban, if the bot isn't able to do that, then it won't kick anyone.
or you can test some pattern with !check to ensure the bot computes properly users's hosts

**Comment by orcus-de** [comment]
hi nirik

I forgot to share a workaround that I found in the meantime with the v 1.5 version.

After I run once a !k (kick), the behavior does return to the one from the 1.4 version (at least it does here) == no matter in which way kickOnMode is set, it does from that on do a kick with !b.

An if one abuses the kickMode (setting it to something else than "b")  allows to turn the feature on and off this way.

Hope it helps.

orcus

**Comment by ncoevoet** [comment]
Feel free to reopen if you find a non working scenario, i wasn't able to reproduce it, even with a fresh install
