### ISSUE TITLE
[Feature Request]  Channel Protection -  flood detection: ignore

### ISSUE THREAD

**Issue by fred0r** [ncoevoet/ChanTracker#36]
would be nice to have the ability to just ignore any input  from users in case of flooding.

`@config channel #channel supybot.plugins.ChanTracker.repeatIgnore True`

**Comment by ncoevoet** [comment]
Hi, by input you means what ?
I don't understand exactly what would you like to have, do you mean to force the bot to ignore commands request from someone if he abuses ?

**Comment by fred0r** [comment]
there are plugins which are triggered by urls pasted by users and when the supybot is not oped, theres no way to 'ignore' these in case of spamming. 
if the bot would be op it could just kick/ban these with chantracker, because of repeating/flooding - but if it has no op theres (afaik) atm no way to 'deny' those requests to be processed.
you could also take a look at https://github.com/oddluck/limnoria-plugins/issues/24 - maybe it helps you to understand what i try to explain :)

**Comment by fred0r** [comment]
[\o/](https://youtu.be/I57hkclh3kk?t=197) - testing right now

**Comment by fred0r** [comment]
works for me - thx!

**Comment by victormamah** [comment]
[GITHUB-202410-GitHubDataProtectionAgreement (1).pdf](https://github.com/user-attachments/files/18431496/GITHUB-202410-GitHubDataProtectionAgreement.1.pdf)
